config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root :to => "welcome#index" #root to: "home#index"
  get '/' , to: "welcome#index"  #default
  get '/articles/index' , to:  "articles#index"  # as: :vertodos






  #C
  get  'articles/new' , to: "articles#new"    # as: :crearnuevo  
  post 'articles' , to: "articles#create" #porque es obligatorio???????                                # crear articulos
  #R
  get 'articles/:identificador' , to: "articles#show"                         #mostrar articulo con su consulta sql
  #U
  get 'articles/:identificador/edit' , to: "articles#edit"                    #editar articulo
  patch 'articles/:identificador' , to: "articles#update" , :as =>  :article    # actualizacion
  #D
  delete 'articles/:identificador' , to: "articles#destroy"

end
#localhost:3000/articles/1/edit
# articles/new
# articles/:identificador
# articles/:identificador/edit
# articles/:identificador

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    has_rich_text :contenidorichtext
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
has_many :articles

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
#before_action :find_article
after_action :authenticate_user! 
#after_action :authenticate_user!


def find_article
    Article.find(params[:identificador])
end

def index 
    @article = Article.all
end

def show
    @article = find_article
end




def new  # instancia nuevo objeto 
    @article = Article.new   #instanciado desde el MODELO y enviar el objeto a la vista
    @article.title = "demo"
    @article.status = "0"
end
def create
    ##desde el fromulario tomale field = NAME , name =  "micampoxd"
   @res= Article.create({
        title:params[:article][:title] ,
        status:params[:article][:status],
        contenidorichtext:params[:article][:contenidorichtext]
})
render json: @res

end

def edit 
    @article = find_article
end
def update
    @article = find_article
    @article.update({
        title:params[:article][:title] ,
        status:params[:article][:status],
        contenidorichtext:params[:article][:contenidorichtext]
})
redirect_to @article
end

def destroy
  @article = find_article
@article.destroy
redirect_to root_path
end





end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/articles/edit.html.erb
<%= render "articles/misparciales/formulario" %>

app/views/articles/index.html.erb
<%= render "articles/misparciales/articles"  %>

app/views/articles/misparciales/_article.html.erb
<h1>
<%=@article.title%>

</h1>

<p>
<%=@article.contenidorichtext%>
</p>


<div>


<%=link_to "eliminar" , @article, method: :delete %>



<%=link_to "eliminarlo"  %>
<%= link_to "actualizar este"  %>

</div>

app/views/articles/misparciales/_articles.html.erb
<table border=true>

<% @article.each do |a| %>
           
              <tr>
              
              <td><%= a.id %></td>
              <td> <%= a.title %></td>
              <td>  <%= a.status %></td>
              <td><%= a.contenidorichtext %> </td>
              <td>detalles </td>
              </tr>
              
              <%end %>

</table>

app/views/articles/misparciales/_formulario.html.erb
<%= form_with(model: @article, local: true) do |form| %>


              <div>
              <%= form.label :title %>
              <%= form.text_field :title %>
              </div>
             
             
             <div>
              <%= form.label :status %>
              <%= form.text_field :status %>
             </div>
             
             
             <div>
             <%= form.label :contenidorichtext %>
             <%= form.rich_text_area :contenidorichtext %>
             </div>
             
             
              <%=form.submit%>
             <% end %>

app/views/articles/misparciales/_navegacion.html.erb
<nav>

<ul>




<%if  user_signed_in? %>
              <li>
              <%= link_to 'cerrar sesion' , destroy_user_session_path  , method: :delete %>
              </li>
<%else%>


<li>
<%= link_to 'iniciar sesion' , new_user_session_path  , method: :get %>
</li>
<li>
<%= link_to 'registro sesion' , new_user_registration_path  , method: :get %>
</li>

<%end%>




<li>
<%= link_to "inicio" , root_path %>
</li>

<li>
<%= link_to "Mis articulos" , articles_index_path %>

</li>

<li>
<%= link_to "escribir" , articles_new_path %>

</li>
</ul>

</nav>

app/views/articles/misparciales/_notificaciones.html.erb
<%if notice%>
              <p class="notice"><%= notice %></p>
              <%end%>
            
              <%if alert%>
                <p class="alert"><%= alert %></p>
              <%end%>

app/views/articles/new.html.erb
<%= render "/articles/misparciales/formulario" %>

app/views/articles/show.html.erb
<%= render "articles/misparciales/article"  %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ExampleBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>



  <%= render "articles/misparciales/notificaciones" %>


  <body>
  <%= render "articles/misparciales/navegacion" %>
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<h1>
Hola mundo 
</h1>